# Generated by Django 5.2.2 on 2025-09-18 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSeries',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(help_text='고유아이디', primary_key=True, serialize=False, verbose_name='고유아이디')),
                ('title', models.CharField(help_text='시리즈명', max_length=64, verbose_name='시리즈명')),
                ('description', models.TextField(blank=True, help_text='시리즈설명', null=True, verbose_name='시리즈설명')),
            ],
            options={
                'verbose_name': '코스 시리즈',
                'verbose_name_plural': '트레킹/하이킹 코스 시리즈',
                'db_table': 'course_series',
            },
        ),
        migrations.CreateModel(
            name='CourseSeriesImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(help_text='고유아이디', primary_key=True, serialize=False, verbose_name='고유아이디')),
                ('url', models.URLField(help_text='URL', max_length=512, verbose_name='URL')),
                ('course_series', models.ForeignKey(help_text='코스 시리즈', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='course.courseseries', verbose_name='코스 시리즈')),
            ],
            options={
                'verbose_name': '코스 시리즈 이미지',
                'verbose_name_plural': '코스 시리즈 이미지',
                'db_table': 'course_series_image',
            },
        ),
    ]
