# Generated by Django 5.2.2 on 2025-09-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseseriesimage',
            name='priority',
            field=models.IntegerField(default=0, help_text='우선순위 (값이 작을 수록 위로 올라간다)', verbose_name='우선순위'),
        ),
        migrations.AddConstraint(
            model_name='courseseriesimage',
            constraint=models.UniqueConstraint(fields=('course_series', 'priority'), name='uq_item_parent_priority'),
        ),
    ]
