# Generated by Django 5.2.2 on 2025-06-14 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyTerm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(help_text='고유아이디', primary_key=True, serialize=False, verbose_name='고유아이디')),
                ('code', models.CharField(help_text='약관 고유 코드', max_length=32, unique=True, verbose_name='약관고유코드')),
                ('name', models.CharField(help_text='약관 이름', max_length=64, verbose_name='약관명')),
            ],
            options={
                'verbose_name': '개인정보동의약관',
                'verbose_name_plural': ' 개인 정보 동의 약관',
                'db_table': 'privacy_terms',
            },
        ),
        migrations.CreateModel(
            name='PrivacyTermVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(help_text='고유아이디', primary_key=True, serialize=False, verbose_name='고유아이디')),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='약관 버전', verbose_name='약관버전')),
                ('title', models.CharField(help_text='약관 제목', max_length=256, verbose_name='약관제목')),
                ('content', models.TextField(help_text='약관 내용', verbose_name='약관내용')),
                ('is_required', models.BooleanField(help_text='필수 여부 (false: 선택)', verbose_name='필수여부')),
                ('privacy_term', models.ForeignKey(db_column='privacy_term_id', help_text='약관 항목', on_delete=django.db.models.deletion.PROTECT, to='privacy_terms.privacyterm', verbose_name='약관항목')),
            ],
            options={
                'verbose_name': '버전별개인정보동의약관',
                'verbose_name_plural': '버전별 개인정보 동의약관',
                'db_table': 'privacy_term_version',
            },
        ),
    ]
