# Generated by Django 5.2.2 on 2025-07-12 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacytermversion',
            name='privacy_term',
            field=models.ForeignKey(db_column='privacy_term_id', help_text='약관 항목', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='privacy_terms.privacyterm', verbose_name='약관항목'),
        ),
    ]
