name: "✨ 기능 요청 (Feature Request)"
description: 프로젝트에 대한 아이디어를 제안해주세요.
title: "[FEAT] "
labels: []
assignees:
  - recoma96
body:
  - type: textarea
    id: related-problem
    attributes:
      label: "겪고 있는 문제가 있나요? (Is your feature request related to a problem?)"
      description: "어떤 문제점이 있는지 명확하고 간결하게 설명해주세요."
      placeholder: "예: 저는 항상 [...] 할 때 불편함을 느낍니다."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "어떤 기능이 필요하신가요? (Describe the solution you'd like)"
      description: "원하는 기능에 대해 명확하고 간결하게 설명해주세요."
      placeholder: "이 기능이 추가되면 좋을 것 같습니다..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "고려해본 다른 대안이 있나요? (Describe alternatives you've considered)"
      description: "고려해본 다른 해결책이나 기능이 있다면 명확하고 간결하게 설명해주세요."
  - type: textarea
    id: additional-context
    attributes:
      label: "추가 정보 (Additional context)"
      description: "기능 요청에 대한 추가적인 내용이나 스크린샷이 있다면 여기에 작성해주세요."