"""create table course_image

Revision ID: 0c9be5c16f98
Revises: 614ca792203b
Create Date: 2025-11-22 19:06:31.292576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c9be5c16f98'
down_revision: Union[str, Sequence[str], None] = '614ca792203b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서 (값이 작을 수록 앞에 둔다)'),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='코스 이미지 리스트'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_image')
    # ### end Alembic commands ###
