"""split description to ab and ba

Revision ID: 1f3476c6d9fe
Revises: eef119624e34
Create Date: 2026-01-21 20:51:44.230334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3476c6d9fe'
down_revision: Union[str, Sequence[str], None] = 'eef119624e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_interval', sa.Column('description_ab', sa.Text(), nullable=True, comment='설명 (정방향)'))
    op.add_column('course_interval', sa.Column('description_ba', sa.Text(), nullable=True, comment='설명 (역방향)'))
    op.drop_column('course_interval', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_interval', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('course_interval', 'description_ba')
    op.drop_column('course_interval', 'description_ab')
    # ### end Alembic commands ###
