"""create place

Revision ID: 3b22c670fca4
Revises: 5ba34702228c
Create Date: 2025-11-10 21:43:49.326022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3b22c670fca4'
down_revision: Union[str, Sequence[str], None] = '5ba34702228c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False, comment='위경도(뷰포트 검색용)'),
    sa.Column('geog', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='위경도(거리, 버퍼 연산)'),
    sa.Column('elevation', sa.Integer(), nullable=True, comment='해발고도(m)'),
    sa.Column('land_address', sa.String(length=128), nullable=True, comment='지번 주소'),
    sa.Column('road_address', sa.String(length=128), nullable=True, comment='도로명 주소'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='장소'
    )
    op.create_index('idx_place_geography', 'place', ['geog'], unique=False, postgresql_using='gist')
    op.create_index('idx_place_geometry', 'place', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_place_geography', table_name='place', postgresql_using='gist')
    op.drop_index('idx_place_geometry', table_name='place', postgresql_using='gist')
    op.drop_table('place')
    # ### end Alembic commands ###
