"""set unique-contraint in place_image

Revision ID: 4ff1d7c882f1
Revises: 7fc70b96bb4d
Create Date: 2025-11-12 22:44:10.877223

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4ff1d7c882f1'
down_revision: Union[str, Sequence[str], None] = '7fc70b96bb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_place_image_place_id_sort_order', 'place_image', ['place_id', 'sort_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_place_image_place_id_sort_order', 'place_image', type_='unique')
    # ### end Alembic commands ###
