"""create kma-mountain-weather-area

Revision ID: 501e9bf51d6e
Revises: 1f3476c6d9fe
Create Date: 2026-02-16 10:31:29.986915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '501e9bf51d6e'
down_revision: Union[str, Sequence[str], None] = '1f3476c6d9fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kma_mountain_weather_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=False, comment='기상청 산악예보 식별번호'),
    sa.Column('name', sa.String(length=16), nullable=False, comment='산악지형 이름'),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False, comment='위경도(뷰포트 검색용)'),
    sa.Column('geog', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='위경도(거리, 버퍼 연산)'),
    sa.Column('elevation', sa.Integer(), nullable=False, comment='해발고도 (m)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kma_mountain_weather_area_geom', table_name='kma_mountain_weather_area', postgresql_using='gist')
    op.drop_index('idx_kma_mountain_weather_area_geog', table_name='kma_mountain_weather_area', postgresql_using='gist')
    op.drop_table('kma_mountain_weather_area')
    # ### end Alembic commands ###
