"""create course interval difficulty table

Revision ID: 581116434553
Revises: 7155a61f9414
Create Date: 2025-11-08 20:51:44.882992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581116434553'
down_revision: Union[str, Sequence[str], None] = '7155a61f9414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_interval_difficulty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False, comment='난이도이름'),
    sa.Column('level', sa.SmallInteger(), nullable=False, comment='난이도 수치(레벨)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='코스 구간 난이도'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_interval_difficulty')
    # ### end Alembic commands ###
