"""alter course_interval_difficulty table

Revision ID: 5ba34702228c
Revises: 581116434553
Create Date: 2025-11-08 20:55:58.309594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba34702228c'
down_revision: Union[str, Sequence[str], None] = '581116434553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_interval_difficulty', sa.Column('code', sa.String(length=16), nullable=False, comment='난이도 코드명(영어)'))
    op.alter_column('course_interval_difficulty', 'name',
               existing_type=sa.VARCHAR(length=16),
               comment='난이도 이름(한글)',
               existing_comment='난이도이름',
               existing_nullable=False)
    op.create_unique_constraint(None, 'course_interval_difficulty', ['code'])
    op.create_unique_constraint(None, 'course_interval_difficulty', ['level'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_interval_difficulty', type_='unique')
    op.drop_constraint(None, 'course_interval_difficulty', type_='unique')
    op.alter_column('course_interval_difficulty', 'name',
               existing_type=sa.VARCHAR(length=16),
               comment='난이도이름',
               existing_comment='난이도 이름(한글)',
               existing_nullable=False)
    op.drop_column('course_interval_difficulty', 'code')
    # ### end Alembic commands ###
