"""alter table course_course_interval add is_reversed

Revision ID: 614ca792203b
Revises: 8c1e159e1aae
Create Date: 2025-11-22 17:50:04.529329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614ca792203b'
down_revision: Union[str, Sequence[str], None] = '8c1e159e1aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_course_interval', sa.Column('is_reversed', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='구간 역방향 여부 (기본: place_a -> place_b)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_course_interval', 'is_reversed')
    # ### end Alembic commands ###
