"""create table course difficulty

Revision ID: 7840890fad1b
Revises: f32279198f69
Create Date: 2025-11-22 09:39:19.632624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7840890fad1b'
down_revision: Union[str, Sequence[str], None] = 'f32279198f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_difficulty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False, comment='난이도 코드명(영어)'),
    sa.Column('name', sa.String(length=16), nullable=False, comment='난이도 이름(한글)'),
    sa.Column('level', sa.SmallInteger(), nullable=False, comment='난이도 수치(레벨)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('level'),
    comment='코스 난이도'
    )
    op.drop_index(op.f('idx_course_interval_geometry'), table_name='course_interval', postgresql_using='gist')
    op.drop_index(op.f('idx_place_geography'), table_name='place', postgresql_using='gist')
    op.drop_index(op.f('idx_place_geometry'), table_name='place', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_place_geometry'), 'place', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_place_geography'), 'place', ['geog'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_course_interval_geometry'), 'course_interval', ['geom'], unique=False, postgresql_using='gist')
    op.drop_table('course_difficulty')
    # ### end Alembic commands ###
