"""create table place_image

Revision ID: 7fc70b96bb4d
Revises: 9d3e00bdaa98
Create Date: 2025-11-12 22:32:40.738125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc70b96bb4d'
down_revision: Union[str, Sequence[str], None] = '9d3e00bdaa98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서 (값이 작을수록 앞에 온다)'),
    sa.Column('place_id', sa.Integer(), nullable=True, comment='장소 ID'),
    sa.Column('url', sa.String(length=256), nullable=False, comment='이미지 전체 URL'),
    sa.Column('title', sa.String(length=32), nullable=True, comment='이미지 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='이미지 설명'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='장소 이미지 리스트'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_image')
    # ### end Alembic commands ###
