"""add is_searchable in place

Revision ID: 9d3e00bdaa98
Revises: 3b22c670fca4
Create Date: 2025-11-12 21:50:18.052243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d3e00bdaa98'
down_revision: Union[str, Sequence[str], None] = '3b22c670fca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place', sa.Column('is_searchable', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='검색 가능 여부'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place', 'is_searchable')
    # ### end Alembic commands ###
