"""alter table course_course_interval unique_constraint

Revision ID: 9ee2e1377a50
Revises: 0c9be5c16f98
Create Date: 2025-11-22 22:37:38.666892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee2e1377a50'
down_revision: Union[str, Sequence[str], None] = '0c9be5c16f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('course_course_interval_unique'), 'course_course_interval', type_='unique')
    op.create_unique_constraint('course_course_interval_unique', 'course_course_interval', ['course_id', 'interval_id', 'position', 'is_reversed'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_course_interval_unique', 'course_course_interval', type_='unique')
    op.create_unique_constraint(op.f('course_course_interval_unique'), 'course_course_interval', ['course_id', 'interval_id', 'position'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
