"""set uniqueconstraint in image tables

Revision ID: c00b18ad1e35
Revises: fb81bd97110a
Create Date: 2025-12-20 21:24:38.086229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00b18ad1e35'
down_revision: Union[str, Sequence[str], None] = 'fb81bd97110a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('course_image_unique_key', 'course_image', ['course_id', 'sort_order'])
    op.create_unique_constraint('course_interval_image_unique_key', 'course_interval_image', ['course_interval_id', 'sort_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_interval_image_unique_key', 'course_interval_image', type_='unique')
    op.drop_constraint('course_image_unique_key', 'course_image', type_='unique')
    # ### end Alembic commands ###
