"""create table kma_middle_areas

Revision ID: d0f088a14dc8
Revises: 02d6c341015b
Create Date: 2026-04-02 08:58:39.349853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f088a14dc8'
down_revision: Union[str, Sequence[str], None] = '02d6c341015b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kma_mid_land_status_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('area', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='기상청 중기육상예보 날씨 지역코드'
    )
    op.create_table('kma_mid_land_temp_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('area', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='기상청 중기육상예보 온도 지역코드'
    )
    op.add_column('course', sa.Column('kma_mid_land_status_area_id', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('kma_mid_land_temp_area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'kma_mid_land_status_area', ['kma_mid_land_status_area_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'course', 'kma_mid_land_temp_area', ['kma_mid_land_temp_area_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_kma_mountain_weather_area_geog'), table_name='kma_mountain_forecast_area', postgresql_using='gist')
    op.drop_index(op.f('idx_kma_mountain_weather_area_geom'), table_name='kma_mountain_forecast_area', postgresql_using='gist')
    op.create_index('idx_kma_mountain_forecast_area_geog', 'kma_mountain_forecast_area', ['geog'], unique=False, postgresql_using='gist')
    op.create_index('idx_kma_mountain_forecast_area_geom', 'kma_mountain_forecast_area', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kma_mountain_forecast_area_geom', table_name='kma_mountain_forecast_area', postgresql_using='gist')
    op.drop_index('idx_kma_mountain_forecast_area_geog', table_name='kma_mountain_forecast_area', postgresql_using='gist')
    op.create_index(op.f('idx_kma_mountain_weather_area_geom'), 'kma_mountain_forecast_area', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_kma_mountain_weather_area_geog'), 'kma_mountain_forecast_area', ['geog'], unique=False, postgresql_using='gist')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'kma_mid_land_temp_area_id')
    op.drop_column('course', 'kma_mid_land_status_area_id')
    op.drop_table('kma_mid_land_temp_area')
    op.drop_table('kma_mid_land_status_area')
    # ### end Alembic commands ###
