"""add columns length and duration in course_interval

Revision ID: eef119624e34
Revises: c00b18ad1e35
Create Date: 2026-01-10 17:32:07.606940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef119624e34'
down_revision: Union[str, Sequence[str], None] = 'c00b18ad1e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_interval', sa.Column('length_m', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='길이(m)'))
    op.add_column('course_interval', sa.Column('duration_ab_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='소요시간(분, 정방향(a->b)'))
    op.add_column('course_interval', sa.Column('duration_ba_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='소요시간(분, 역방향(b->a)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_interval', 'duration_ba_minutes')
    op.drop_column('course_interval', 'duration_ab_minutes')
    op.drop_column('course_interval', 'length_m')
    # ### end Alembic commands ###
