"""add table course_interval

Revision ID: f32279198f69
Revises: 4ff1d7c882f1
Create Date: 2025-11-20 22:05:16.962511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f32279198f69'
down_revision: Union[str, Sequence[str], None] = '4ff1d7c882f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_interval',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRINGZ', srid=4326, dimension=3, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='간선 GPX데이터 (위도, 경도, 고도)'),
    sa.Column('place_a_id', sa.Integer(), nullable=False, comment='지점A'),
    sa.Column('place_b_id', sa.Integer(), nullable=False, comment='지점B'),
    sa.Column('course_interval_difficulty_id', sa.Integer(), nullable=True, comment='구간 난이도'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.CheckConstraint('place_a_id < place_b_id', name='ck_course_interval_undirected_order'),
    sa.ForeignKeyConstraint(['course_interval_difficulty_id'], ['course_interval_difficulty.id'], ),
    sa.ForeignKeyConstraint(['place_a_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['place_b_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='코스 구간 (Place 사이를 잇는 간선)'
    )
    op.create_index('idx_course_interval_geometry', 'course_interval', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_course_interval_geom_geometry', table_name='course_interval', postgresql_using='gist')
    op.drop_table('course_interval')
    # ### end Alembic commands ###
