"""create table in alpha 0.3.0

Revision ID: f73deb7928d8
Revises: 
Create Date: 2026-04-04 11:44:14.203476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'f73deb7928d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_difficulty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False, comment='난이도 코드명(영어)'),
    sa.Column('name', sa.String(length=16), nullable=False, comment='난이도 이름(한글)'),
    sa.Column('level', sa.SmallInteger(), nullable=False, comment='난이도 수치(레벨)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('level'),
    comment='코스 난이도'
    )
    op.create_table('course_interval_difficulty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False, comment='난이도 코드명(영어)'),
    sa.Column('name', sa.String(length=16), nullable=False, comment='난이도 이름(한글)'),
    sa.Column('level', sa.SmallInteger(), nullable=False, comment='난이도 수치(레벨)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('level'),
    comment='코스 구간 난이도'
    )
    op.create_table('course_style',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False, comment='코드명'),
    sa.Column('name', sa.String(length=16), nullable=False, comment='이름(한글)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='코스 형식(스타일)'
    )
    op.create_table('kma_mid_land_status_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('area', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='기상청 중기육상예보 날씨 지역코드'
    )
    op.create_table('kma_mid_land_temp_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('area', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='기상청 중기육상예보 온도 지역코드'
    )
    op.create_table('kma_mountain_forecast_area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=False, comment='기상청 산악예보 식별번호'),
    sa.Column('name', sa.String(length=16), nullable=False, comment='산악지형 이름'),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False, spatial_index=False), nullable=False, comment='위경도(뷰포트 검색용)'),
    sa.Column('geog', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False, comment='위경도(거리, 버퍼 연산)'),
    sa.Column('elevation', sa.Integer(), nullable=False, comment='해발고도 (m)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_kma_mountain_forecast_area_geog', 'kma_mountain_forecast_area', ['geog'], unique=False, postgresql_using='gist')
    op.create_index('idx_kma_mountain_forecast_area_geom', 'kma_mountain_forecast_area', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False, spatial_index=False), nullable=False, comment='위경도(뷰포트 검색용)'),
    sa.Column('geog', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False, comment='위경도(거리, 버퍼 연산)'),
    sa.Column('elevation', sa.Integer(), nullable=True, comment='해발고도(m)'),
    sa.Column('land_address', sa.String(length=128), nullable=True, comment='지번 주소'),
    sa.Column('road_address', sa.String(length=128), nullable=True, comment='도로명 주소'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('is_searchable', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='검색 가능 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='장소'
    )
    op.create_index('idx_place_geog', 'place', ['geog'], unique=False, postgresql_using='gist')
    op.create_index('idx_place_geom', 'place', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('nickname', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('can_access_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='어드민 접속 가능 여부'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='최근 로그인 날짜'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='사용자'
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('course_difficulty_id', sa.Integer(), nullable=False),
    sa.Column('course_style_id', sa.Integer(), nullable=False),
    sa.Column('kma_mid_land_status_area_id', sa.Integer(), nullable=True),
    sa.Column('kma_mid_land_temp_area_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['course_difficulty_id'], ['course_difficulty.id'], ),
    sa.ForeignKeyConstraint(['course_style_id'], ['course_style.id'], ),
    sa.ForeignKeyConstraint(['kma_mid_land_status_area_id'], ['kma_mid_land_status_area.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kma_mid_land_temp_area_id'], ['kma_mid_land_temp_area.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='코스'
    )
    op.create_table('course_interval',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description_ab', sa.Text(), nullable=True, comment='설명 (정방향)'),
    sa.Column('description_ba', sa.Text(), nullable=True, comment='설명 (역방향)'),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRINGZ', srid=4326, dimension=3, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False, comment='간선 GPX데이터 (위도, 경도, 고도)'),
    sa.Column('place_a_id', sa.Integer(), nullable=False, comment='지점A'),
    sa.Column('place_b_id', sa.Integer(), nullable=False, comment='지점B'),
    sa.Column('course_interval_difficulty_id', sa.Integer(), nullable=True, comment='구간 난이도'),
    sa.Column('length_m', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='길이(m)'),
    sa.Column('duration_ab_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='소요시간(분, 정방향(a->b)'),
    sa.Column('duration_ba_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='소요시간(분, 역방향(b->a)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.CheckConstraint('place_a_id < place_b_id', name='ck_course_interval_undirected_order'),
    sa.ForeignKeyConstraint(['course_interval_difficulty_id'], ['course_interval_difficulty.id'], ),
    sa.ForeignKeyConstraint(['place_a_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['place_b_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='코스 구간 (Place 사이를 잇는 간선)'
    )
    op.create_index('idx_course_interval_geom', 'course_interval', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('place_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서 (값이 작을수록 앞에 온다)'),
    sa.Column('place_id', sa.Integer(), nullable=True, comment='장소 ID'),
    sa.Column('url', sa.String(length=256), nullable=False, comment='이미지 전체 URL'),
    sa.Column('title', sa.String(length=32), nullable=True, comment='이미지 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='이미지 설명'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'sort_order', name='uq_place_image_place_id_sort_order'),
    comment='장소 이미지 리스트'
    )
    op.create_table('course_course_interval',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('interval_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, comment='구간 순서'),
    sa.Column('is_reversed', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='구간 역방향 여부 (기본: place_a -> place_b)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interval_id'], ['course_interval.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'interval_id', 'position', 'is_reversed', name='course_course_interval_unique'),
    comment='코스 - 구간 사이의 중간 테이블'
    )
    op.create_table('course_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서 (값이 작을 수록 앞에 둔다)'),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'sort_order', name='course_image_unique_key'),
    comment='코스 이미지 리스트'
    )
    op.create_table('course_interval_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서 (값이 작을 수록 앞에 둔다)'),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_interval_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['course_interval_id'], ['course_interval.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_interval_id', 'sort_order', name='course_interval_image_unique_key'),
    comment='구간 이미지 리스트'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_interval_image')
    op.drop_table('course_image')
    op.drop_table('course_course_interval')
    op.drop_table('place_image')
    op.drop_index('idx_course_interval_geom', table_name='course_interval', postgresql_using='gist')
    op.drop_table('course_interval')
    op.drop_table('course')
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index('idx_place_geom', table_name='place', postgresql_using='gist')
    op.drop_index('idx_place_geog', table_name='place', postgresql_using='gist')
    op.drop_table('place')
    op.drop_index('idx_kma_mountain_forecast_area_geom', table_name='kma_mountain_forecast_area', postgresql_using='gist')
    op.drop_index('idx_kma_mountain_forecast_area_geog', table_name='kma_mountain_forecast_area', postgresql_using='gist')
    op.drop_table('kma_mountain_forecast_area')
    op.drop_table('kma_mid_land_temp_area')
    op.drop_table('kma_mid_land_status_area')
    op.drop_table('course_style')
    op.drop_table('course_interval_difficulty')
    op.drop_table('course_difficulty')
    # ### end Alembic commands ###
