"""create table course_interval_image

Revision ID: fb81bd97110a
Revises: 9ee2e1377a50
Create Date: 2025-12-06 11:06:53.416573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb81bd97110a'
down_revision: Union[str, Sequence[str], None] = '9ee2e1377a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_interval_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서 (값이 작을 수록 앞에 둔다)'),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_interval_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("(now() AT TIME ZONE 'Asia/Seoul')"), nullable=False),
    sa.ForeignKeyConstraint(['course_interval_id'], ['course_interval.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='구간 이미지 리스트'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_interval_image')
    # ### end Alembic commands ###
