# Generated by Django 5.2.2 on 2025-06-14 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(help_text='유저아이디', primary_key=True, serialize=False, verbose_name='유저아이디')),
                ('email', models.EmailField(help_text='로그인 및 인증에 사용되는 이메일', max_length=256, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(help_text='화면에 보여지는 이름', max_length=32, verbose_name='닉네임')),
                ('is_staff', models.BooleanField(blank=True, default=False, help_text='관리자 페이지에 접속할 수 있는 계정 여부', verbose_name='관리자여부')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text='M: 남, F: 여, null: 정하지 않음', max_length=1, null=True, verbose_name='성별')),
                ('birthday', models.CharField(blank=True, help_text='생일', max_length=8, null=True, verbose_name='생일')),
                ('profile_image_url', models.CharField(blank=True, help_text='프로필이미지URL', max_length=256, null=True, verbose_name='프로필이미지URL')),
                ('inactivated_at', models.DateTimeField(blank=True, help_text='탈퇴한 날짜', null=True, verbose_name='탈톼날짜')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user',
            },
        ),
    ]
