# --- build stage ---
FROM node:24-alpine AS builder

WORKDIR /app

# 의존성 설치
COPY package*.json ./
RUN npm i

# 소스코드 복사 
COPY . .

# 빌드 시점 env
ENV PUBLIC_API_ENDPOINT=/api \
    API_ENDPOINT=http://trailine-api-server:8080/api \
    NAVER_MAPS_API_CLIENT=

# 웹파일 빌드
RUN npm run build

EXPOSE 4321

CMD ["npm", "run", "preview"]
